### ISSUE TITLE
Unity used too much RAM during the training process, resulting in non-response.

### ISSUE THREAD

**Issue by huypham37** [huypham37/AIML-UM-14#1]
# Unity used too much RAM during the training process, resulting in non-response

### Problem
During the training process with the ML-Agents SoccerTwos environment, Unity consumed an excessive amount of RAM, leading to non-responsiveness. The training could not proceed, and the system became unresponsive, requiring a manual restart.

### Configuration
Here is the configuration used:
```yaml
behaviors:
  SoccerTwos:
    trainer_type: ppo
    self_play:
      play_against_latest_model_ratio: 0.5
    save_steps: 20000
    team_change: 10000
    hyperparameters:
      batch_size: 1024
      buffer_size: 20400
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 5.0e6
    time_horizon: 64
```

Steps to Reproduce

	1.	Set up the SoccerTwos environment using the configuration above.
	2.	Start training with the command:

```mlagents-learn config.yaml --run-id=ppo_soccer_twos --env=build/SoccerTwos --train```

### Expected Behavior
Training should proceed without Unity consuming excessive RAM, allowing the system to remain responsive.
